name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up SSH key for Azure VM
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}

      # Deploy to Azure VM via SSH
      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            # Navigate to the project directory (change this to your VM path)
            cd /home/azureuser/orchestrator

            # Pull the latest changes from GitHub (assuming you're using Git in the VM)
            git pull origin main

            docker-compose down && docker-compose up -d

          EOF
