name: Update Submodule to Latest api-application

on:
  schedule:
    - cron: '*/25 * * * *'  # Run every 5 minutes
  push:
    branches:
      - main
    paths:
      - 'api-application/**'  # Trigger when the submodule's files change

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository orchestrator (this will also checkout submodules)
      - name: Checkout repository orchestrator
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are fetched

      # Initialize the submodule
      - name: Initialize submodule
        run: |
          git submodule update --init --recursive

      # Update the submodule to the latest commit from api-application's main branch
      - name: Update submodule to latest commit from api-application's main branch
        run: |
          git submodule update --remote api-application

      # Configure Git user for commit (set locally for this repository)
      - name: Set Git user for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Check for changes in the submodule reference (which is tracked in the parent repository)
      - name: Check for changes in the submodule reference
        run: |
          git diff --exit-code || (git add api-application && git commit -m "Update submodule api-application" && git push)
